package expression

import (
	"sort"
)

// ScalarProgram is an immutable, opaque compiled scalar expression. Its
// representation is private; consumers choose the evaluator matching
// ResultType and cannot inspect or construct graph nodes.
type ScalarProgram struct {
	nodes  []scalarNode
	root   int
	result ResultType

	deps      Dependencies
	canonical string
	cost      ProgramCost

	upperBound      int
	upperBoundKnown bool
}

// ResultType returns the scalar root type.
func (p *ScalarProgram) ResultType() ResultType {
	if p == nil {
		return ResultInvalid
	}
	return p.result
}

// EvaluateBool evaluates a Bool root using the caller's read-only lookup.
func (p *ScalarProgram) EvaluateBool(lookup Lookup) (bool, error) {
	if p == nil {
		return false, evaluateError("program", "NIL_PROGRAM", "scalar program is nil")
	}
	if p.result != ResultBool {
		return false, evaluateError("root", "TYPE_MISMATCH", "program root is not bool")
	}
	return p.evalBool(p.root, lookup, "root", len(p.nodes)+1)
}

// EvaluateInt64 evaluates an Int64 root using the caller's read-only lookup.
func (p *ScalarProgram) EvaluateInt64(lookup Lookup) (int64, error) {
	if p == nil {
		return 0, evaluateError("program", "NIL_PROGRAM", "scalar program is nil")
	}
	if p.result != ResultInt64 {
		return 0, evaluateError("root", "TYPE_MISMATCH", "program root is not int64")
	}
	return p.evalInt64(p.root, lookup, "root", len(p.nodes)+1)
}

// EvaluateStrings evaluates a Strings root and returns sorted distinct values.
func (p *ScalarProgram) EvaluateStrings(lookup Lookup) ([]string, error) {
	if p == nil {
		return nil, evaluateError("program", "NIL_PROGRAM", "scalar program is nil")
	}
	if p.result != ResultStrings {
		return nil, evaluateError("root", "TYPE_MISMATCH", "program root is not strings")
	}
	values, err := p.evalStrings(p.root, lookup, "root", len(p.nodes)+1)
	if err != nil {
		return nil, err
	}
	return uniqueStrings(values), nil
}

// EvaluateUint64s evaluates a Uint64s root and returns sorted distinct values.
func (p *ScalarProgram) EvaluateUint64s(lookup Lookup) ([]uint64, error) {
	if p == nil {
		return nil, evaluateError("program", "NIL_PROGRAM", "scalar program is nil")
	}
	if p.result != ResultUint64s {
		return nil, evaluateError("root", "TYPE_MISMATCH", "program root is not uint64s")
	}
	values, err := p.evalUint64s(p.root, lookup, "root", len(p.nodes)+1)
	if err != nil {
		return nil, err
	}
	return uniqueUint64s(values), nil
}

// Canonical returns the stable expression identity generated by the scalar
// compiler. It is independent of JSON whitespace and object field order.
func (p *ScalarProgram) Canonical() string {
	if p == nil {
		return ""
	}
	return p.canonical
}

// Dependencies returns the deterministic Fact and attribute dependency set.
func (p *ScalarProgram) Dependencies() Dependencies {
	if p == nil {
		return Dependencies{}
	}
	return p.deps
}

// Cost returns the compiled expression resource summary.
func (p *ScalarProgram) Cost() ProgramCost {
	if p == nil {
		return ProgramCost{}
	}
	return p.cost
}

// CollectionUpperBound returns a conservative compile-time bound for a
// collection root. A false result means that no finite bound was provable.
func (p *ScalarProgram) CollectionUpperBound() (int, bool) {
	if p == nil || (p.result != ResultStrings && p.result != ResultUint64s) {
		return 0, false
	}
	return p.upperBound, p.upperBoundKnown
}

func (p *ScalarProgram) validNode(id int, path string, remaining int) error {
	if id < 0 || id >= len(p.nodes) {
		return evaluateError(path, "INVALID_NODE", "scalar node %d is invalid", id)
	}
	if remaining <= 0 {
		return evaluateError(path, "CYCLE", "scalar expression contains a cycle")
	}
	return nil
}

func (p *ScalarProgram) evalBool(id int, lookup Lookup, path string, remaining int) (bool, error) {
	if err := p.validNode(id, path, remaining); err != nil {
		return false, err
	}
	node := p.nodes[id]
	switch node.kind {
	case kindBoolLiteral:
		return node.boolValue, nil
	case kindBoolAnd:
		for index, child := range node.children {
			value, err := p.evalBool(child, lookup, path+".items["+itoa(index)+"]", remaining-1)
			if err != nil {
				return false, err
			}
			if !value {
				return false, nil
			}
		}
		return true, nil
	case kindBoolOr:
		for index, child := range node.children {
			value, err := p.evalBool(child, lookup, path+".items["+itoa(index)+"]", remaining-1)
			if err != nil {
				return false, err
			}
			if value {
				return true, nil
			}
		}
		return false, nil
	case kindBoolNot:
		value, err := p.evalBool(node.value, lookup, path+".value", remaining-1)
		if err != nil {
			return false, err
		}
		return !value, nil
	case kindInt64Equal, kindInt64NotEqual, kindInt64Less, kindInt64LessOrEqual, kindInt64Greater, kindInt64GreaterOrEqual:
		left, err := p.evalInt64(node.left, lookup, path+".left", remaining-1)
		if err != nil {
			return false, err
		}
		right, err := p.evalInt64(node.right, lookup, path+".right", remaining-1)
		if err != nil {
			return false, err
		}
		return compareInt64(node.kind, left, right), nil
	case kindStringsEqual, kindStringsNotEqual, kindStringsEmpty, kindStringsContains, kindStringsContainsAny, kindStringsContainsAll, kindStringsIntersects:
		return p.evalStringPredicate(node, lookup, path, remaining)
	case kindUint64sEqual, kindUint64sNotEqual, kindUint64sEmpty, kindUint64sContains, kindUint64sContainsAny, kindUint64sContainsAll, kindUint64sIntersects:
		return p.evalUint64Predicate(node, lookup, path, remaining)
	default:
		return false, evaluateError(path, "TYPE_MISMATCH", "scalar node %s does not produce bool", node.kind)
	}
}

func (p *ScalarProgram) evalInt64(id int, lookup Lookup, path string, remaining int) (int64, error) {
	if err := p.validNode(id, path, remaining); err != nil {
		return 0, err
	}
	node := p.nodes[id]
	switch node.kind {
	case kindInt64Literal:
		return node.int64Value, nil
	case kindInt64Lookup:
		if lookup == nil {
			return 0, evaluateError(path, "NIL_LOOKUP", "lookup is nil")
		}
		value, ok := lookup.Int64(node.source, node.name)
		if !ok {
			return 0, evaluateError(path, "MISSING_VALUE", "int64 value %q is missing from source %s", node.name, node.source)
		}
		return value, nil
	case kindInt64Step:
		value, err := p.evalInt64(node.input, lookup, path+".input", remaining-1)
		if err != nil {
			return 0, err
		}
		position := sort.Search(len(node.steps), func(index int) bool { return node.steps[index].at > value })
		if position == 0 {
			return node.steps[0].value, nil
		}
		return node.steps[position-1].value, nil
	case kindInt64Clamp:
		value, err := p.evalInt64(node.value, lookup, path+".value", remaining-1)
		if err != nil {
			return 0, err
		}
		minimum, err := p.evalInt64(node.minimum, lookup, path+".min", remaining-1)
		if err != nil {
			return 0, err
		}
		maximum, err := p.evalInt64(node.maximum, lookup, path+".max", remaining-1)
		if err != nil {
			return 0, err
		}
		if minimum > maximum {
			return 0, evaluateError(path, "INVALID_CLAMP_BOUNDS", "clamp minimum exceeds maximum")
		}
		if value < minimum {
			return minimum, nil
		}
		if value > maximum {
			return maximum, nil
		}
		return value, nil
	case kindInt64Add, kindInt64Sub, kindInt64Min, kindInt64Max:
		left, err := p.evalInt64(node.left, lookup, path+".left", remaining-1)
		if err != nil {
			return 0, err
		}
		right, err := p.evalInt64(node.right, lookup, path+".right", remaining-1)
		if err != nil {
			return 0, err
		}
		switch node.kind {
		case kindInt64Add:
			return saturatingAdd(left, right), nil
		case kindInt64Sub:
			return saturatingSub(left, right), nil
		case kindInt64Min:
			if right < left {
				return right, nil
			}
		case kindInt64Max:
			if right > left {
				return right, nil
			}
		}
		return left, nil
	default:
		return 0, evaluateError(path, "TYPE_MISMATCH", "scalar node %s does not produce int64", node.kind)
	}
}

func (p *ScalarProgram) evalStrings(id int, lookup Lookup, path string, remaining int) ([]string, error) {
	if err := p.validNode(id, path, remaining); err != nil {
		return nil, err
	}
	node := p.nodes[id]
	switch node.kind {
	case kindStringsLiteral:
		return node.strings, nil
	case kindStringsLookup:
		if lookup == nil {
			return nil, evaluateError(path, "NIL_LOOKUP", "lookup is nil")
		}
		values, ok := lookup.Strings(node.source, node.name)
		if !ok {
			return nil, evaluateError(path, "MISSING_VALUE", "string values %q are missing from source %s", node.name, node.source)
		}
		return values, nil
	case kindStringsUnion:
		var values []string
		for index, child := range node.children {
			part, err := p.evalStrings(child, lookup, path+".items["+itoa(index)+"]", remaining-1)
			if err != nil {
				return nil, err
			}
			values = append(values, part...)
		}
		return values, nil
	default:
		return nil, evaluateError(path, "TYPE_MISMATCH", "scalar node %s does not produce strings", node.kind)
	}
}

func (p *ScalarProgram) evalUint64s(id int, lookup Lookup, path string, remaining int) ([]uint64, error) {
	if err := p.validNode(id, path, remaining); err != nil {
		return nil, err
	}
	node := p.nodes[id]
	switch node.kind {
	case kindUint64sLiteral:
		return node.uint64s, nil
	case kindUint64sLookup:
		if lookup == nil {
			return nil, evaluateError(path, "NIL_LOOKUP", "lookup is nil")
		}
		values, ok := lookup.Uint64s(node.source, node.name)
		if !ok {
			return nil, evaluateError(path, "MISSING_VALUE", "uint64 values %q are missing from source %s", node.name, node.source)
		}
		return values, nil
	case kindUint64sUnion:
		var values []uint64
		for index, child := range node.children {
			part, err := p.evalUint64s(child, lookup, path+".items["+itoa(index)+"]", remaining-1)
			if err != nil {
				return nil, err
			}
			values = append(values, part...)
		}
		return values, nil
	default:
		return nil, evaluateError(path, "TYPE_MISMATCH", "scalar node %s does not produce uint64s", node.kind)
	}
}

func (p *ScalarProgram) evalStringPredicate(node scalarNode, lookup Lookup, path string, remaining int) (bool, error) {
	leftPath := path + ".left"
	if node.kind == kindStringsEmpty {
		leftPath = path + ".values"
	}
	left, err := p.evalStrings(node.value, lookup, leftPath, remaining-1)
	if err != nil {
		return false, err
	}
	left = uniqueStrings(left)
	switch node.kind {
	case kindStringsEmpty:
		return len(left) == 0, nil
	case kindStringsContains:
		return containsString(left, node.name), nil
	}
	right, err := p.evalStrings(node.right, lookup, path+".right", remaining-1)
	if err != nil {
		return false, err
	}
	right = uniqueStrings(right)
	switch node.kind {
	case kindStringsEqual:
		return equalStrings(left, right), nil
	case kindStringsNotEqual:
		return !equalStrings(left, right), nil
	case kindStringsContainsAny, kindStringsIntersects:
		return intersectsStrings(left, right), nil
	case kindStringsContainsAll:
		return containsAllStrings(left, right), nil
	default:
		return false, evaluateError(path, "TYPE_MISMATCH", "scalar node %s does not produce bool", node.kind)
	}
}

func (p *ScalarProgram) evalUint64Predicate(node scalarNode, lookup Lookup, path string, remaining int) (bool, error) {
	leftPath := path + ".left"
	if node.kind == kindUint64sEmpty {
		leftPath = path + ".values"
	}
	left, err := p.evalUint64s(node.value, lookup, leftPath, remaining-1)
	if err != nil {
		return false, err
	}
	left = uniqueUint64s(left)
	switch node.kind {
	case kindUint64sEmpty:
		return len(left) == 0, nil
	case kindUint64sContains:
		return containsUint64(left, node.uint64s[0]), nil
	}
	right, err := p.evalUint64s(node.right, lookup, path+".right", remaining-1)
	if err != nil {
		return false, err
	}
	right = uniqueUint64s(right)
	switch node.kind {
	case kindUint64sEqual:
		return equalUint64s(left, right), nil
	case kindUint64sNotEqual:
		return !equalUint64s(left, right), nil
	case kindUint64sContainsAny, kindUint64sIntersects:
		return intersectsUint64s(left, right), nil
	case kindUint64sContainsAll:
		return containsAllUint64s(left, right), nil
	default:
		return false, evaluateError(path, "TYPE_MISMATCH", "scalar node %s does not produce bool", node.kind)
	}
}

func compareInt64(kind scalarKind, left, right int64) bool {
	switch kind {
	case kindInt64Equal:
		return left == right
	case kindInt64NotEqual:
		return left != right
	case kindInt64Less:
		return left < right
	case kindInt64LessOrEqual:
		return left <= right
	case kindInt64Greater:
		return left > right
	case kindInt64GreaterOrEqual:
		return left >= right
	default:
		return false
	}
}

func saturatingAdd(left, right int64) int64 {
	if right > 0 && left > int64(^uint64(0)>>1)-right {
		return int64(^uint64(0) >> 1)
	}
	if right < 0 && left < -int64(^uint64(0)>>1)-1-right {
		return -int64(^uint64(0)>>1) - 1
	}
	return left + right
}

func saturatingSub(left, right int64) int64 {
	if right > 0 && left < -int64(^uint64(0)>>1)-1+right {
		return -int64(^uint64(0)>>1) - 1
	}
	if right < 0 && left > int64(^uint64(0)>>1)+right {
		return int64(^uint64(0) >> 1)
	}
	return left - right
}

func uniqueStrings(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	out := append([]string(nil), values...)
	sort.Strings(out)
	write := 1
	for read := 1; read < len(out); read++ {
		if out[read] != out[write-1] {
			out[write] = out[read]
			write++
		}
	}
	return out[:write]
}

func uniqueUint64s(values []uint64) []uint64 {
	if len(values) == 0 {
		return nil
	}
	out := append([]uint64(nil), values...)
	sort.Slice(out, func(i, j int) bool { return out[i] < out[j] })
	write := 1
	for read := 1; read < len(out); read++ {
		if out[read] != out[write-1] {
			out[write] = out[read]
			write++
		}
	}
	return out[:write]
}

func equalStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func containsString(values []string, target string) bool {
	index := sort.SearchStrings(values, target)
	return index < len(values) && values[index] == target
}

func intersectsStrings(left, right []string) bool {
	leftIndex, rightIndex := 0, 0
	for leftIndex < len(left) && rightIndex < len(right) {
		switch {
		case left[leftIndex] < right[rightIndex]:
			leftIndex++
		case left[leftIndex] > right[rightIndex]:
			rightIndex++
		default:
			return true
		}
	}
	return false
}

func containsAllStrings(values, needles []string) bool {
	for _, needle := range needles {
		if !containsString(values, needle) {
			return false
		}
	}
	return true
}

func equalUint64s(left, right []uint64) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func containsUint64(values []uint64, target uint64) bool {
	index := sort.Search(len(values), func(index int) bool { return values[index] >= target })
	return index < len(values) && values[index] == target
}

func intersectsUint64s(left, right []uint64) bool {
	leftIndex, rightIndex := 0, 0
	for leftIndex < len(left) && rightIndex < len(right) {
		switch {
		case left[leftIndex] < right[rightIndex]:
			leftIndex++
		case left[leftIndex] > right[rightIndex]:
			rightIndex++
		default:
			return true
		}
	}
	return false
}

func containsAllUint64s(values, needles []uint64) bool {
	for _, needle := range needles {
		if !containsUint64(values, needle) {
			return false
		}
	}
	return true
}

func itoa(value int) string {
	// Child indexes are bounded by JSONLimits.MaxChildren. Avoid fmt on the
	// successful evaluator path while keeping the error path readable.
	if value == 0 {
		return "0"
	}
	var buf [20]byte
	index := len(buf)
	for value > 0 {
		index--
		buf[index] = byte('0' + value%10)
		value /= 10
	}
	return string(buf[index:])
}
